# Generated by Django 6.0 on 2026-01-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='organizations.organization')),
                ('garden_id', models.AutoField(primary_key=True, serialize=False)),
                ('garden_name', models.CharField(max_length=30)),
                ('environment', models.CharField(choices=[('I', 'indoor'), ('O', 'outdoor'), ('G', 'greenhouse')], default='I', max_length=1)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='GardenInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(editable=False)),
                ('invitee_identifier', models.CharField(help_text='The contact identifier for the invitee, email, phone number, social media handle, etc.', max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gardens.garden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='gardens.garden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GardenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
            options={
                'ordering': ['organization', 'user'],
                'abstract': False,
            },
        ),
    ]
