# Generated by Django 6.0 on 2026-01-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='garden_name',
        ),
    ]
