# Generated by Django 6.0 on 2026-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_remove_garden_garden_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='is_public',
        ),
    ]
