# Generated by Django 6.0.1 on 2026-02-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_remove_garden_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GardenInvitation',
        ),
    ]
