# Generated by Django 6.0.1 on 2026-02-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
