# Generated by Django 6.0.1 on 2026-02-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
