# Generated by Django 6.0.1 on 2026-02-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge'),
        ('users', '0006_remove_user_bio'),
    ]

    operations = [
    ]
