# Generated by Django 4.2.27 on 2026-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
