# Generated by Django 6.0 on 2026-01-08 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(blank=True, max_length=25, null=True)),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plants', to='gardens.garden')),
            ],
        ),
    ]
