# Generated by Django 6.0 on 2026-01-04 21:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('soil_type_used', models.CharField(choices=[('C', 'Clay'), ('SD', 'Sand'), ('ST', 'Silt'), ('L', 'Loam'), ('P', 'Peat'), ('CH', 'Chalk'), ('D', 'Default Soil')], default='D', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_ph', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('current_temp_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_moisture', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_light', models.CharField(choices=[('FS', 'Full sun'), ('BS', 'Bright sun'), ('MD', 'Medium light'), ('LL', 'Low light')], default='MD', max_length=2)),
                ('last_fertilized', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
