# Generated by Django 6.0 on 2025-12-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=150)),
                ('soil_moisture_min', models.FloatField()),
                ('soil_moisture_max', models.FloatField()),
                ('soil_ph_min', models.FloatField()),
                ('soil_ph_max', models.FloatField()),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clayey', 'Clayey'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('saline', 'Saline')], max_length=50)),
                ('light_min', models.FloatField()),
                ('light_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('air_humidity_min', models.FloatField()),
                ('air_humidity_max', models.FloatField()),
                ('nitrogen_min', models.FloatField()),
                ('nitrogen_max', models.FloatField()),
                ('phosphorus_min', models.FloatField()),
                ('phosphorus_max', models.FloatField()),
                ('potassium_min', models.FloatField()),
                ('potassium_max', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
