# Generated by Django 6.0 on 2025-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrequirement',
            name='air_humidity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='air_humidity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='latin_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='light_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='light_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='nitrogen_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='nitrogen_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='phosphorus_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='phosphorus_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='potassium_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='potassium_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='soil_moisture_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='soil_moisture_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='soil_ph_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='soil_ph_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantrequirement',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
