# Generated by Django 4.2.27 on 2026-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='nickname',
            field=models.CharField(max_length=25),
        ),
    ]
