# Generated by Django 6.0 on 2025-12-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plantrequirement_air_humidity_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrequirement',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clayey', 'Clayey'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('saline', 'Saline')], max_length=50, null=True),
        ),
    ]
