# Generated by Django 6.0 on 2026-01-20 17:19

import django.db.models.deletion
import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_initial'),
        ('plants', '0003_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardens.garden'),
        ),
    ]
