# Generated by Django 6.0 on 2026-01-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_initial'),
        ('plants', '0004_alter_plant_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardens.garden'),
        ),
    ]
