# Generated by Django 6.0 on 2026-02-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_remove_garden_is_public'),
        ('plants', '0005_alter_plant_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardens.garden'),
        ),
    ]
